### ISSUE TITLE
Delay padding for the mp3 encoder

### ISSUE THREAD

**Issue by ProsperDevelopment** [superpoweredSDK/SuperpoweredLatency#3]
I'm still struggling with gapless looping of mp3. I have problems getting the number of samples/ ms of silence in the end and beginning.

What I understand the padding delay differ from encoders and encoders, is there any specifcation of the encoder that SuperpoweredLatency uses?

Is there any example project that have mp3 gapless looping?

**Comment by superpoweredSDK** [comment]
The SuperpoweredLatency app doesn't play or loop any audio files. This app measures the round-trip audio latency of a mobile device.
