### ISSUE TITLE
Consistently getting incorrect results on Pixel XL running Android 8.0

### ISSUE THREAD

**Issue by dturner** [superpoweredSDK/SuperpoweredLatency#4]
Device tested: Pixel XL running Android 8.0 (OPR6.170623.012)

Steps to reproduce: 

- Connect headset jack to powered speaker (or use Loopback dongle)
- Run Latency Test 

Expected outcome: 

- Latency reported at <20ms

Actual outcome: 

- Results seem to start at around 36ms, then drop down in steps of about 4ms. Average ends up being around 26ms (6-8ms higher than expected)

**Comment by superpoweredSDK** [comment]
We can reproduce the same with the Nexus 6P as well. 
We've already reported this on the "AAudio documentation and headers for O DP1" thread on 25th July: https://groups.google.com/forum/#!topic/android-ndk/Zm8f9YQHc7M
The Android Audio Team did not return with anything since then.

**Comment by dturner** [comment]
A reference implementation for measuring round-trip latency can be found at: https://github.com/gkasten/drrickorang/tree/master/LoopbackApp. Using this app I consistently get ~17ms.

**Comment by superpoweredSDK** [comment]
Hi Don,

If I recall correctly, the Rick O’Rang Loopback only emits one beep -- while Superpowered Latency app emits 10, of which we take the average of - as such, in normal environmental conditions there will be some variance per test/beep in round-trip audio latency. 

As you know, our code is open-source and can be inspected here:

https://github.com/superpoweredSDK/SuperpoweredLatency/blob/master/Android/app/src/main/jni/latencyMeasurer.cpp

Our app works both on iOS and Android -- and as I commented above -- we reported the very same issues to the Android audio team earlier this year. 

What do you think explains the difference in results between Rick O’Rang and Superpowered Latency?

**Comment by superpoweredSDK** [comment]
Did a quick session with some terminal messages. Until Android 8.0 the input and output callbacks did monotonically follow each other: input, output, input, output, ...

In Android 8.0/Nexus 6P, the order is now this: 4 inputs, 4 outputs, 4 inputs, 4 outputs...

This means increased (!!!!) round-trip latency via OpenSL ES. I'll try to find some time to re-structure our measurement app soon.

**Comment by superpoweredSDK** [comment]
Something is not right with the Rick O'Rang app too. The glitch test always returns with 2-3 glitches on the Nexus 6P, so it's round-trip latency measurement can not be trusted.
We've checked it's code, the RX and TX buffer count of 1 is not enough to cover the multiple inputs/outputs, so the measurement by the Rick O'Rang is false.

**Comment by superpoweredSDK** [comment]
Updated the app to correctly support Android 8.
Measurements on previous Android versions are not affected.
