### ISSUE TITLE
Possible to limit number of beeps?

### ISSUE THREAD

**Issue by JeremyPacker** [superpoweredSDK/SuperpoweredLatency#7]
Hello,

Thanks for releasing this sample!!

If I wanted to limit the number of beeps from 10 to 5, will that affect accuracy and how can we apply this?

Thank you!

**Comment by deepakrokz** [comment]
Hi @JeremyPacker ,

Can you please address this [issue](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/issues/462)
